services:
    project-task:
        container_name: project-task-manager
        build:
            context: .
        ports:
            - 8080:8080
        depends_on:
            - mysql
    mysql:
        container_name: mysql-db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: caed_db
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
  mysql-data: